[package]
name = "eoplus"
version = "1.0.0-RC1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
antlr-rust = "=0.3.0-beta"
